### ISSUE TITLE
Durable subscription does not ack message

### ISSUE THREAD

**Issue by nick-zh** [byrnedo/php-nats-streaming#3]
I might be doing something wrong, but when i try to subscribe to a channel and consume a msg, it seems
the message doesnt get ack'ed properly, when i subscribe again, i still get the same message

```
$options = new ConnectionOptions();
$options->setClientID("test-consumer");
$client = new Connection($options);
$client->connect();

$subOptions = new SubscriptionOptions();
$subOptions->setStartAt(StartPosition::LastReceived());
$subOptions->setDurableName("testname");

$sub = $client->subscribe('test-channel', function (Msg $message) {
    printf("Data: %s\r\n", $message->getData());
}, $subOptions);



$client->wait(1);

$sub->close();

$client->close();
```

**Comment by byrnedo** [comment]
Hi,
Going to throw together a test to double check. When you set LastReceived
you will get the last 'ack'd message just FYI

**Comment by nick-zh** [comment]
@byrnedo yes thx, i have last received set, so i set my wait to 3, but somehow i get all 3 messages back that i have (is that correct?), i thought i would only get the last one of the 3 back. Also, strangely, after the first call to read 3, the second call throws me an error:
```
PHP Fatal error:  Uncaught NatsStreaming\Exceptions\TimeoutException: timeout occured waiting for response in /home/nick/projects/nats-consumer/vendor/byrnedo/php-nats-streaming/src/NatsStreaming/Subscription.php:254
Stack trace:
#0 /home/nick/projects/nats-consumer/vendor/byrnedo/php-nats-streaming/src/NatsStreaming/Subscription.php(200): NatsStreaming\Subscription->closeOrUnsubscribe(false)
#1 /home/nick/projects/nats-consumer/Consumer.php(30): NatsStreaming\Subscription->unsubscribe()
#2 {main}
```
First i was suspecting permission problems, but when i tested this with the admin user, i got the same result. I will investigate further this week and share if i found something

**Comment by byrnedo** [comment]
Yeah, you're right, should only be the last of the 3 you get. I was travelling yesterday and didn't get a proper chance, will have a go today at fixing this.

**Comment by byrnedo** [comment]
Ah, was really silly, I was publishing acks via the streaming publish, not the plain nats publish. So you were dead right. Fixing now and cleaning up a test.

**Comment by byrnedo** [comment]
try updating to 0.1.1 and have a look to see if it works for you now.

**Comment by nick-zh** [comment]
@byrnedo thx for the quick reply, i still get the same behaviour, not sure if i am doing something wrong. just for my understanding when does which ack need to be published where? or does the streaming server ack on his side, and then routes it to the core nats?
my publish code is really simple, maybe that helps as well:

```
$connectionOptions = new ConnectionOptions();
$connectionOptions->setNatsOptions($options);
$connectionOptions->setClientID("test-pusher");
$client = new Connection($connectionOptions);
$client->connect();
$client()->publish("test-channel", "some message");
```
server side i have the following config:
```
channels: {
    "test-channel": {
        max_subs: 100
    }
}

store_limits: {
    max_age: 0
}

authorization {

  ADMIN = {
    publish = ">"
    subscribe = ">"
  }

  users = [
    {user: admin, password: admin, permissions: $ADMIN}
  ]
}
```
maybe i am missing something obvious

**Comment by byrnedo** [comment]
Is the client definitely at version 0.1.1? You can check by looking in the README.md in vendor/byrnedo/php-nats-streaming.

When you publish, stan sends an ack to us saying that it got it. Right now the publish code explicitly waits for that ack or will throw a timeout.

When subscribing, we send an ack to stan after each sub callback is run.
If using the isManualAck mode then it's up to the user to call `$message->ack()` in the subscription cb.

Can you check if you still get full replay if you remove the `$sub->close()` line? Apparently closing the connection is an implicit close of all subscriptions. What you're doing should work though.

**Comment by byrnedo** [comment]
You can see the test I wrote here:
https://github.com/byrnedo/php-nats-streaming/blob/master/tests/Unit/ConnectionTest.php#L120

Is the flow of what you're doing like so:

1. Publish n message
2. Durable sub with last received and check that you get message 1 through n
3. Close connection
4. Connect and create new durable sub and see that you get message n?

Edit: Durable names don't support LastReceived. It will ignore that option.

**Comment by nick-zh** [comment]
@byrnedo Thx for the clarification on the ack stuff. 
Silly me though, i tinkered around with my code, testing some other stuff and i had a $sub->unsubscribe while retesting. As far as i can see, it works like a charm now, issue can be closed.
Thx a lot for the quick fix and the fast reaction mate.

**Comment by byrnedo** [comment]
You're very welcome! Thanks for trying out the repo, glad to fix that ack problem!
