### ISSUE TITLE
Incorrect behaviour with two consumers on same subject (durable sub)

### ISSUE THREAD

**Issue by nick-zh** [byrnedo/php-nats-streaming#4]
Heya @byrnedo 

So i am creating to consumers on the same subject, they each create their seperate subscription (durable).
I start both. I would expect, that if a message (for that subject) lands in the queue, it is consumed by both.
Only the last client started seems to get the message though. When i restart the client i started first, it gets the message too though.

Cheers,
Nick

**Comment by byrnedo** [comment]
Hey!
So, same subject and same durable name yeah?
Hmm. Need to check how the go client handles it.
If nats sends me the same sub id for both (which I'm guessing it does) then I can have an array of callbacks for each sub instead.

Edit: are we talking separate clients too?
If the client id is the same on 2 clients then you'll get the behaviour you're seeing I think.

**Comment by nick-zh** [comment]
@byrnedo always same client id

**Use case 1**
Seperate durable names
*Expected:* Both consumer, consume the same messages at the same time
*Actual behaviour:* The consumer started last consumes his messages, second consumer is idle.
After killing both and restarting the one that was idle, it consumes all its messages.

**Use case 2**
Same durable name
*Expected:* They consume the messages as a whole (something like one gets one half and the other the other)
*Actual behaviour:* Only one consumer, consumes all messages (the one started latest)

Maybe in use case 2, this is a wanted behaviour, i dont know. Let me know if you need more info.

Cheers,
Nick

**Comment by byrnedo** [comment]
Can you give me some pseudo code of what you're doing? Are you running these separate clients on different php processes?

AFAIK the durable name affects the last read message mostly, that stan records clientId + durable name and the last ack'd message position so that when restarting a subscriber there that it will receive the first unsent or unack'd message, unless a different start position is requested.

There are limitations with this php implementation at least with the `$c->wait(n)` thing. If you have one client subscribing on 2 channels, if you expected a total of 4 messages on chan 1, and 5 on chan 2, you'd have to `wait(9)`;

**Comment by nick-zh** [comment]
@byrnedo i have basically the same script twice (with different durable names / or the same) and start them in another shell, code is this:

```
options = new ConnectionOptions();
$options->setClientID("test-consumer");
$client = new Connection($options);
$client->connect();

$subOptions = new SubscriptionOptions();
$subOptions->setStartAt(StartPosition::SequenceStart());
$subOptions->setDurableName("test-sub");

$sub = $client->subscribe('test-subject', function (Msg $message) {
    printf("Data: %s\r\n", $message->getData());
}, $subOptions);



$client->wait(100);

$sub->close();

$client->close();
```

then while both are running, i produce a couple of messages and check which lands where

**Comment by byrnedo** [comment]
Ok @nick-zh , I'll try and recreate. 

Another thing: I was thinking about changing `wait` out to be `listen($timeout)` or something like that instead. Would that seem more usable to you? 
Or maybe have both? 
The reason is the wait(n) has issues depending on timing and then if someone decided to publish within a subscription then it all goes to hell.
Any thoughts?

**Comment by nick-zh** [comment]
@byrnedo nice thx. yeah ```listen($timeout)``` would actually be nicer, i dont like the wait approach too much. i guess having both would be nice, maybe there is a usecase where you really want to wait for an amount, but in my case, listen would be nicer. let me know if i can be of some help, atm i have limited time, but let me know if i can somehow help out. if i find time over the weekend, i want to dig a bit deeper into the code anyway

**Comment by byrnedo** [comment]
Thanks, yeah, might do with help. Especially conceptually. I was trying to keep things as close to the phpnats interface as possible but there a limitations there.

I pushed a branch called feature/improve-ack. I've added `$sub->wait(n)` now instead. 

Basically, it tracks to which sub each  received message belongs to. If you get n for your sub it'll return, or timeout.

If we got `y` messages for another sub during the process, and then call `$sub->wait(y)` later, it'll return immediately.

Edit: @nick-zh

**Comment by byrnedo** [comment]
I've added a test on that branch: `testMultipleDurableSubscription`. It replicates your scenario (I think) and seems to work with the new `$sub->wait()` setup. 
I'm not sure that using the same client id for 2 clients is a great idea though by the way, the first `$c->close()` will close both connections from stan's point of view. The second disconnect will then get an error `unknown clientID` from the server.

**Comment by byrnedo** [comment]
I had a look around and see that [php-amqplib's Channel class](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AbstractChannel.php#L316) does basically the same thing but caches other messages received during the wait. If another channel calls wait then only then does the sub's callbacks get run. I might implement that if it sounds reasonable to you @nick-zh.

**Comment by nick-zh** [comment]
@byrnedo thx for all the work, sry was quite busy on the WE, i will have a look later today on your branch.
Yes the approach sounds very interesting, so if there are methods we can dispatch to, it does, if we get some others unexpected, it caches the call away for later, right? I only had a quick look, but the approach sounds very interesting and useful to me

**Comment by byrnedo** [comment]
No worries, I didn't have so much to do haha!
The only thing about the sub wait is that there would also need to be a
general $c->wait() as well for just blocking and processing all. That's
doable though.

**Comment by nick-zh** [comment]
@byrnedo alright so if i have to different clientIds it seems to work fine.
However if i have the same client ids, different durable names, results in the same "old" behaviour.

General question: How would i implement several consumers on the same subscription, to scale consuming, somehow i was unable to do this (tried same clientid, same durable name)

edit: tested on branch [feature/improve-ack](https://github.com/byrnedo/php-nats-streaming/tree/feature/improve-ack)

**Comment by byrnedo** [comment]
do you want both consumers to get same messages @nick-zh ?

**Comment by byrnedo** [comment]
If you want to distribute work you can use a durable queue. So a `queueSubscribe` with a durable name. Each messages will be given to only 1 client in the queue group.

**Comment by nick-zh** [comment]
@byrnedo thx a lot, somehow i still get only messages for one consumer (with ```queueSubscribe```), then again, i dont know how it is distributed :)
I will try to figure it out. Should i close the issue, or will you, when you merge [feature/improve-ack](https://github.com/byrnedo/php-nats-streaming/tree/feature/improve-ack) ?

**Comment by byrnedo** [comment]
I think they just do round-robin.
If it's the same client id, the last one probably wins with the same durablename.

AFAIK to have a worker group for a subject/channel it should be:
- unique client id per consumer
- unique or non unique durable name (doesn't matter, coupled to client id)
- shared queue group name

So consumer 1:
ClientID: consumer1, DurableName: foobar, QueueGroup: workergroup
Then consumer 2:
ClientID: consumer2, DurableName: foobar, QueueGroup: workergroup

I can close it when I merge!

**Comment by nick-zh** [comment]
@byrnedo thx for the insight, somehow, this results for me in the consumer1 and consumer2 consuming the same messages though, not a feature that i will be using, so no problem for me ;)

**Comment by byrnedo** [comment]
hmm, somethings up. It should mean the only get unique messages from the channel.
I'll try and dig into whatever's going wrong.

**Comment by byrnedo** [comment]
@nick-zh: I made a big push to develop now. 
Sorry for the confusion earlier, I didn't quite get how the durables worked.
I made an integration test that seems to work now, `tests/Integration/MultipleConsumerTest.php@testDurableConsumer`. 
When creating two subsequent consumers after each other with same client id and durable name, the second consumer picks up where the other left off.

**Comment by byrnedo** [comment]
Going to close this for now.

**Comment by byrnedo** [comment]
@nick-zh There was incorrect behaviour before v 0.2.4 with queue groups, should now be fixed, just FYI
