### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getSid() on null

### ISSUE THREAD

**Issue by mardachevdv** [byrnedo/php-nats-streaming#5]
``` 
Error: Call to a member function getSid() on null in vendor/byrnedo/php-nats-streaming/src/NatsStreaming/TrackedNatsRequest.php on line 58
```

**Comment by byrnedo** [comment]
Hi @mardachevdv ,  what version do you have?
And do you have more of a stack trace?

**Comment by mardachevdv** [comment]
Hi @byrnedo 
"byrnedo/php-nats-streaming": "^0.2.2"

**Comment by byrnedo** [comment]
@mardachevdv I have a fix, was a silly error. Will change a test to cover this case.

**Comment by mardachevdv** [comment]
@byrnedo 
Thanks!

**Comment by byrnedo** [comment]
0.2.3 has a fix for that. Thanks for reporting!
