### ISSUE TITLE
queue subscription

### ISSUE THREAD

**Issue by mardachevdv** [byrnedo/php-nats-streaming#6]
@byrnedo 
I have another question
I try to create queue subscription, but always receive all messages to all subscribers
I don't know it's related to your code or something else
maybe you can help me with that

my code
```
//subscribe
$natsOpts = new \NatsStreaming\ConnectionOptions();
$natsOpts->setClientID(md5(uniqid((string)microtime(), true)));
$natsOpts->setClusterID($config['nats']['cluster.id']);
$natsOpts->setNatsOptions(new \Nats\ConnectionOptions([
    'host' => $config['nats']['host'],
    'port' => $config['nats']['port'],
    'token' => $config['nats']['auth.token'],
]));
$natsClient = new \NatsStreaming\Connection($natsOpts);
$natsClient->connect();

$subOptions = new \NatsStreaming\SubscriptionOptions();
$subOptions->setDurableName($options['task']);
$subOptions->setManualAck(true);


$natsSub = $natsClient->queueSubscribe(
    $options['task'],
    $options['task'],
    $callback,
    $subOptions
);
```

**Comment by byrnedo** [comment]
@mardachevdv will check out what's going on

**Comment by byrnedo** [comment]
I've recreated it, will try and figure out why it's starting at 0.

**Comment by byrnedo** [comment]
@mardachevdv Fixed in version 0.2.4

**Comment by mardachevdv** [comment]
@byrnedo 
Thank you!

**Comment by byrnedo** [comment]
No problem, again thanks for reporting. Sorry about the teething problems! :/

**Comment by byrnedo** [comment]
@mardachevdv also, would be great if you can confirm that it's working as expected

I've changed the queue sub test to check but just want to be sure.

**Comment by mardachevdv** [comment]
@byrnedo 
yes, now everything is ok
